name: nos3

services:
  emqx:
    image: emqx:latest
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx_ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    ports:
      - 1883:1883

  gather-service:
    build:
      context: ./Microservices/gather-service
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    depends_on:
      emqx:
        condition: service_healthy

  gather-mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  ticket-service:
    build:
      context: ./Microservices/ticket-service
      dockerfile: ./Dockerfile
    ports:
      - 8001:8001
    depends_on:
      emqx:
        condition: service_healthy

  ticket-mongodb:
    image: mongo:latest
    command: mongod --port 27018
    ports:
      - 27018:27018
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  ekuiper:
    image: lfedge/ekuiper:latest
    ports:
      - 9081:9081
    restart: unless-stopped
    user: root
    volumes:
      - ekuiper_data:/kuiper/data
      - ekuiper_log:/kuiper/log
    environment:
      MQTT_SOURCE__DEFAULT__SERVER: "tcp://emqx:1883"
      KUIPER__BASIC__CONSOLELOG: "true"
      KUIPER__BASIC__IGNORECASE: "false"
    depends_on:
      emqx:
        condition: service_healthy

  ekuiper-manager:
    image: emqx/ekuiper-manager:latest
    ports:
      - 9082:9082
    restart: unless-stopped
    environment:
      DEFAULT_EKUIPER_ENDPOINT: "http://ekuiper:9081"
        

volumes:
  ekuiper_data:
  ekuiper_log: