apiVersion: apps/v1
kind: Deployment
metadata:
  name: ekuiper-manager-deployment
  labels:
    app: ekuiper-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ekuiper-manager
  template:
    metadata:
      labels:
        app: ekuiper-manager
    spec:
      containers:
      - image: emqx/ekuiper-manager:latest
        name: ekuiper-manager
        ports:
        - containerPort: 9082
        env:
        - name: DEFAULT_EKUIPER_ENDPOINT
          value: "http://ekuiper:9081"
---
apiVersion: v1
kind: Service
metadata:
  name: ekuiper-manager
spec:
  selector:
    app: ekuiper-manager
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 9082
    targetPort: 9082