apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gather-mongodb-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gather-mongodb-deployment
  labels:
    app: gather-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gather-mongodb
  template:
    metadata:
      labels:
        app: gather-mongodb
    spec:
      containers:
      - image: mongo:latest
        name: gather-mongodb
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: admin  
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: password
        volumeMounts:
          - name: gather-mongodb-data
            mountPath: /data/db
      volumes:
      - name: gather-mongodb-data
        persistentVolumeClaim:
          claimName: gather-mongodb-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: gather-mongodb
spec:
  selector:
    app: gather-mongodb
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017