apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ekuiper-autoscaler
spec:
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 50
        type: Utilization
    type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ekuiper-deployment